### ISSUE TITLE
Custom post type 

### ISSUE THREAD

**Issue by Mte90** [WebDevStudios/WDS-Log-Post#9]
Is possible to have a custom post type

**Comment by tw2113** [comment]
in what regards? Like changing the post type used for the logging? or changing what triggers a log event? or something else?

**Comment by Mte90** [comment]
Yes sorry, my idea is to set a custom post type with a custom taxonomy so is possible to have a specific log.

**Comment by tw2113** [comment]
Not personally sure. Not seeing much for hooks available, to be honest. Worst case scenario would be forking the repo and amending to fit your needs, and that's really not that horrific. :)

**Comment by Mte90** [comment]
Yes i was thinking to fork to have that feature but i think that this library is on github and composer will be useful to have only one.

**Comment by Mte90** [comment]
Pull request done :-)

**Comment by tw2113** [comment]
Looking things over with one of the other devs for the plugin. Feel free to use your forked version, by all obvious means, until we act. :)

**Comment by Mte90** [comment]
Sure no problem, I am already using my version in the meantime of the approval :-)
